# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: teampikachu08
service: brian-kwong-express-sl
useDotenv: true

plugins:
  - "serverless-offline"

provider:
  name: aws
  runtime: nodejs20.x
  environment: ${file(./env.js):env}
  timeout: 300
  httpApi:
    cors: true

functions:
  api:
    handler: src/index.handler
    timeout: 300
    url: true
    events:
      - httpApi: "*"

package:
  include:
    - src/data/**
